### ISSUE TITLE
twoliter bootstrapping container tagging

### ISSUE THREAD

**Issue by webern** [bottlerocket-os/twoliter#12]
### Description

Design an implement a way for Twoliter to re-use its bootstrapping container from one invocation to the next.
It needs to tag the built container in a consistent way based on the version of Twoliter that is running.
That way, it can refrain from re-building the container if the expected version is available.

### Definition of Done

When Twoliter no longer needs to build its bootstrapping container every time it is invoked.
Also, when Twoliter builds the container because the version of the existing container does not match what it needs.

#### Depends on:

- [x] https://github.com/bottlerocket-os/twoliter/issues/10

```
id: texec_container_ver
epic: twoliter_exec
```

Related to https://github.com/bottlerocket-os/bottlerocket/issues/2669

**Comment by bcressey** [comment]
Maybe `twoliter` could hash itself via `/proc/self/exe` to compute a short hash for its running version. Then we could avoid using the "latest" tag for anything.

**Comment by webern** [comment]
Putting this on hold with the wontfix label because it isn't clear that we will ever be using a "bootstrapping" container, and we have solved the adding of scripts to the SDK with secrets mounts.

**Comment by webern** [comment]
This isn't the intended path anymore. Closing.
