### ISSUE TITLE
align and update aws-rust-sdk, tough, tough-kms, and tough-ssm versions

### ISSUE THREAD

**Issue by webern** [bottlerocket-os/twoliter#124]
A series of prerequisites exists, after which we will want to align all of our aws-rust-sdk, tough, tough-kms, and tough-ssm versions:
- [x] https://github.com/awslabs/coldsnap/issues/302
- [x] https://github.com/awslabs/tough/issues/747
- [x] Release tough and tuftool
- [x] #123

# Definition of Done

Only one version of the AWS Rust SDK crates are present in Twoliter's Cargo.lock, and those versions are all 1.x.

**Comment by rpkelly** [comment]
Should this cover TestSys, Pubsys, and Coldsnap as well?

**Comment by webern** [comment]
> Should this cover TestSys, Pubsys, and Coldsnap as well?

Yes. Coldsnap has been updated to v1 but I think it might still expose types.

**Comment by webern** [comment]
Done!
