### ISSUE TITLE
tuftool failing to add-key

### ISSUE THREAD

**Issue by jmt-lab** [bottlerocket-os/twoliter#150]
## What is happening?
When building bottlerocket with an Infra.toml and signing-key specified, it is failing to call tuftool root add-key. It appears that tuftool now only expects one argument instead of two.

## Error

```
error: unexpected argument 'aws-kms:///...' found

Usage: tuftool root add-key [OPTIONS] <PATH>

For more information, try '--help'.
Returned 2: tuftool root add-key '/home/fedora/bottlerocket/roles/.tmpmHyITS' 'aws-kms:///... --role root --role snapshot --role targets --role timestamp
```

## Reproduction steps
Checkout bottlerocket develop copy the tools/pubsys/Infra.toml.example comment out signing_keys or specify it and try cargo make.

**Comment by bcressey** [comment]
I hit a similar error in the local key path:
```
21:21:27 [INFO] Found infra config at path: /home/fedora/brdev/Infra.toml
21:21:27 [INFO] Didn't find root role in Infra.toml, generating...
error: unexpected argument 'file:///home/fedora/brdev/keys/default.pem' found

Usage: tuftool root add-key [OPTIONS] <PATH>

For more information, try '--help'.
Returned 2: tuftool root add-key '/home/fedora/brdev/roles/.tmpVjLfSn' 'file:///home/fedora/brdev/keys/default.pem' --role root --role snapshot --role targets --role timestamp
```

For me this happened when I removed `roles/default.root.json` but not `keys/default.pem`.

**Comment by bcressey** [comment]
It looks like we need to add `--key` to the [pubsys invocation](https://github.com/bottlerocket-os/twoliter/blob/6fec72b1db44052b9f7b58a7a44bd1f114f4ca6e/tools/pubsys-setup/src/main.rs#L128) after the `-k` / `--key` option was added in https://github.com/awslabs/tough/commit/0345cc8bc59721b80e977e566fb5e88e1dd84ce4.
