### ISSUE TITLE
twoliter: generate kit metadata file off Cargo.toml build-kit definitions

### ISSUE THREAD

**Issue by jmt-lab** [bottlerocket-os/twoliter#255]
We need to after or before the build of rpms for a local kit, generate a metadata file at 

```
build/kit/<kit>/<kit>-<version>-<arch>-<build_id>.json
```

That contains the kit metadata that rpm2kit will embed in the generated OCI image to track the kits dependencies when published as an external kit using pubsys. 

The metadata file should follow the below schematic

```json
{
    "schema-version": 1,
    "name": "<kit-name>",
    "version": "<kit-version>",
    "sdk": {
         "name": "<sdk-name>",
         "version": "<sdk-version>",
         "vendor": "<sdk-vendor>"
     },
     "kit": [
         {"name": "<kit-name>", "version": "<kit-version>", "vendor": "<kit-vendor>"}
     ]
}
```

**Comment by webern** [comment]
Is the `"kit"` array the list of kits that it depends on? Should it be `"kit-dependencies"`? If it depends on a local kit, how will we know that local kit's vendor?
