### ISSUE TITLE
twoliter: lock creation and resolution

### ISSUE THREAD

**Issue by jmt-lab** [bottlerocket-os/twoliter#256]
We need to write an algorithm that given a Twoliter.toml will resolve all needed kit dependencies and generate a Twoliter.lock

We should also update the twoliter commands that need sdk or kits to use the lock file instead of Project file alone. 

We should also create a `twoliter update` command that the user can use to update their lockfile

**Comment by webern** [comment]
Related, possibly duplicative of #18
