### ISSUE TITLE
RPM macros defined twice

### ISSUE THREAD

**Issue by arnaldo2792** [bottlerocket-os/twoliter#388]
### What I expected to happen

I expect that `%undefine`'ing any macro provided by the Bottlerocket SDK will actually undefine them

### What actually happened

The macros are still defined after calling `%undefine` on them

### How to reproduce

In any spec file in the Core Kit, attempt to undefine `_cross_go_os`. The macro will still be defined:

```spec
%undefine _cross_go_os
echo Cross GO OS: %{_cross_go_os}
```

This prints `Cross GO OS: linux`. Only after a second `%undefine` the macro is actually undefined:

```
%undefine _cross_go_os
echo Cross GO OS: %{_cross_go_os}
```

This prints `Cross GO OS: %{_cross_go_os}` which is expected. I tested a few other macros and got the same results.

### Potential fixes

I think the problem comes from these two lines:

https://github.com/bottlerocket-os/twoliter/blob/1afb8aaaf46221718b14c3954b087cedcb066178/twoliter/embedded/build.Dockerfile#L56
https://github.com/bottlerocket-os/twoliter/blob/1afb8aaaf46221718b14c3954b087cedcb066178/twoliter/embedded/build.Dockerfile#L78

In a test environment (`sleep infinity` while building a package and `nsenter -a -t <pid>`), I tried removing `$HOME/.rpmmacros`, and the double `%undefine` wasn't needed:

```bash
[root@buildkitsandbox /] su builder
bash-5.2$ rpm --undefine '_cross_arch' --eval '%{_cross_arch}'
x86_64
bash-5.2$ rm -rf ~/.rpmmacros
bash-5.2$ rpm --undefine '_cross_arch' --eval '%{_cross_arch}'
%{_cross_arch}
bash-5.2$ rpm --eval '%{_cross_arch}'
x86_64
bash-5.2$
```

One potential solution could be removing the `$HOME/.rpmmacros` file and only use the "system-wide" configuration at `/etc/rpm/`.  The alternative being removing the "system-wide" configuration.

**Comment by bcressey** [comment]
> One potential solution could be removing the $HOME/.rpmmacros file and only use the "system-wide" configuration at /etc/rpm/.

The `/etc/rpm/macros` file is the copy I'd try to eliminate. It's been a while since https://github.com/bottlerocket-os/twoliter/commit/b753a8e435ef9ca48701ddc159203803d331227c but I think the point was to have the same RPM macros defined for both the `root` and `builder` users, or possibly also to make `dnf builddep` work.
