### ISSUE TITLE
remove generate-readme

### ISSUE THREAD

**Issue by webern** [bottlerocket-os/twoliter#39]
Remove generate-readme from the Twoliter project. Ensure that the README information for any package that happens to be currently using generate-readme is not duplicated. We should choose either main.rs/lib.rs *or8 README.md as the home for our documentation.

I've never been a fan of the generated README's anyway and Ben said:

> sources/generate-readme
>
>
> Should we just remove this dependency if we're not going to generate README's for everything? We could just patch that dependency out of `bottlerocket-variant` and `parse-datetime` build scripts after the import.

_Originally posted by @bcressey in https://github.com/bottlerocket-os/twoliter/issues/37#issuecomment-1692429512_

**Comment by stmcginnis** [comment]
The tool is also unmaintained, so it causes some very old and duplicate dips to be pulled in.

**Comment by webern** [comment]
On the Bottlerocket side I recommend that we "fork" the project by pasting its code (and attributing the code with license etc) directly into the generate readme crate.

I contacted the maintainer, who did reply to me once positively about adding maintainers, but haven't heard back since I replied to that reply.
