### ISSUE TITLE
Make application inventory generation kit agnostic

### ISSUE THREAD

**Issue by ginglis13** [bottlerocket-os/twoliter#397]
Based on discussion in https://github.com/bottlerocket-os/twoliter/pull/384

When application-inventory is constructed for building a Bottlerocket variant, the `bottlerocket-` prefix of a package name is removed if the package is sourced from the bottlerocket-core-kit:

https://github.com/bottlerocket-os/twoliter/blob/a54ac6d89ac48e862a3e90ad9f6490f7790057bb/twoliter/embedded/rpm2img#L230-L235

Some options:
* We could have a "remove vendor prefix" option somewhere for variant builders to make this decision for themselves

* The inventory will list bottlerocket-glibc (etc) instead of glibc.
  * This option has implications for [BRSAs defined in kits](https://github.com/bottlerocket-os/bottlerocket-core-kit/tree/develop/advisories); the `package-name` must match exactly the package name that results in variant application inventory.

The latter is likely the simplest, however an overridden definition of `%{__cross_os}` or `%{cross_vendor}` would result in application inventory -> BRSA mismatch.

**Comment by cbgbt** [comment]
> The latter is likely the simplest, however an overridden definition of %{__cross_os} or %{cross_vendor} would result in application inventory -> BRSA mismatch.

I hadn't considered this! Although, overriding those macros would mean that you are rebuilding the software, and the BRSAs in the core-kits advisory metadata may not apply anymore anyways.

**Comment by cbgbt** [comment]
I could see a case where a downstream would still want advisories to apply to their custom build, though.

e.g. suppose you are downstream "foobar" and you are rebuilding the kernel from `bottlerocket-core-kit` as "foobar-kernel-6.1" but you only apply a few minimal patches. You might wish, out of convenience, for upstream's advisory information to apply and alert you when you need to perform a rebuild. In that case it could be beneficial for your inventory to just rename "foobar-kernel-6.1" to "kernel-6.1".
