### ISSUE TITLE
dynamic gomodules

### ISSUE THREAD

**Issue by webern** [bottlerocket-os/twoliter#88]
TODO - write this issue.

GOMODULES are kind of hardcoded in Makefile.toml
Might not be an issue? But maybe we should discover them?

Ben's suggestion from https://github.com/bottlerocket-os/twoliter/pull/108#discussion_r1377922765

> Potentially we want a contract like:
>
> Twoliter will search the sources path for Cargo.lock and go.mod files and download the referenced Rust crates and Go modules prior to package builds.
>
> And eventually support for .twoliterignore files to suppress this behavior by excluding certain paths.

**Comment by ecpullen** [comment]
This was completed for alpha build in #108
